YALB-686: Bug: Error when user ID is null
yalesites-org/yale_cas pull request #1
Opened 2022-08-30 06:03 UTC by nJim

## [YALB-686: Bug: Error when user ID is null](https://yaleits.atlassian.net/browse/YALB-686)

### Description of work
- Checks if the user ID exists before altering the form. This prevents changes to the user-add form where the logic in the alter hook does not apply.

### Functional testing steps:
- [ ] Install the CAS module or update to this version. 
- [ ] Visit the user-add form and verify that you can see the form. Previously this white-screened and threw and error.

2022-08-30 19:25 UTC, marcb4k requested changes
While it no longer white screens, I am getting an error if I visit that page: 

```Notice: Undefined variable: cas_username in yale_cas_form_user_form_alter() (line 28 of modules/custom/yale_cas/yale_cas.module).```

It appears that line 22 is setting that variable, but if line 21 is empty, line 22 never fires so that variable will not exist.

2022-08-31 04:15 UTC, nJim commented
@marcb4k Good call. Careless mistake on my part. I changed this to a ternary to ensure we always have a value. Ready for rereview.

2022-08-31 17:37 UTC, marcb4k approved these changes

2022-08-31 17:37 UTC, marcb4k commented
Works for me now! Approved.

2022-09-01 14:45 UTC, merged